services:
  - type: web
    name: essaie-1-backend
    env: node
    plan: free
    branch: main
    buildCommand: npm ci
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
